# Generated by Django 4.2.13 on 2024-05-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image_url",
            field=models.URLField(null=True),
        ),
    ]
